### ISSUE TITLE
visidata.nvim launch a tmux session

### ISSUE THREAD

**Issue by pbnewsom** [Willem-J-an/visidata.nvim#1]
How do I edit this configuration so that visidata is launched in a new tmux session instead of a terminal?
The config is pointed to the usr/bin/tmux file, but that's all. 

My enviroment is termux on an android device and everything runs perfect except for this. 

Thank you.

**Comment by Willem-J-an** [comment]
Maybe you need to write a script that will create a new tmux session, then attach to it. Nvim-dap would launch the script and maybe it works? I'm not a tmux user, so no guarantees 😁

**Comment by pbnewsom** [comment]
It turns out you provided an answer in the Q&A (#656 on Aug 20, 2022) that solves my issue.
Thanks
