### ISSUE TITLE
where should the user config for python go?

### ISSUE THREAD

**Issue by kraxli** [Willem-J-an/visidata.nvim#2]
this looks very promising :-) - thanks for it!

I just struggle with the location to put the config you describe in [Usage](https://github.com/Willem-J-an/visidata.nvim?tab=readme-ov-file#usage) to. Can you help me on this?

**Comment by Willem-J-an** [comment]
1&2 you can put in the config function for lazy as is shown in the installation part. 3 you can set in your launch.json file.
